/**
 * Report export. Premium only.
 *
 * The API returns HTML rather than PDF. Producing a PDF needs a headless browser or a
 * rendering engine, which would add a large dependency to every deployment of this
 * service. The desktop app already has a renderer, so it converts this HTML locally,
 * and the HTML itself is a perfectly good deliverable to share or print on its own.
 */
import { SEVERITIES } from "../constants/index.js";

const SEVERITY_COLOURS = {
  critical: "#b3261e",
  high: "#d93025",
  medium: "#f9ab00",
  low: "#1a73e8",
  info: "#5f6368",
};

/** Escapes text before it goes into HTML, so evidence cannot inject markup. */
function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatDate(value) {
  if (!value) return "not recorded";
  const date = value.toDate ? value.toDate() : new Date(value);
  return Number.isNaN(date.getTime()) ? "not recorded" : date.toISOString().replace("T", " ").slice(0, 19);
}

function severityRank(finding) {
  const index = SEVERITIES.indexOf(String(finding.severity || "").toLowerCase());
  return index === -1 ? SEVERITIES.length : index;
}

function renderFinding(finding) {
  const severity = String(finding.severity || "info").toLowerCase();
  const colour = SEVERITY_COLOURS[severity] ?? SEVERITY_COLOURS.info;

  return `
  <section class="finding">
    <h3>
      <span class="badge" style="background:${colour}">${escapeHtml(severity.toUpperCase())}</span>
      ${escapeHtml(finding.title)}
    </h3>
    <dl>
      <dt>Category</dt><dd>${escapeHtml(finding.category)}</dd>
      <dt>OWASP risk</dt><dd>${escapeHtml((finding.owasp ?? []).join(", ") || "not mapped")}</dd>
      <dt>Confidence</dt><dd>${escapeHtml(finding.confidence ?? "confirmed")}</dd>
      ${finding.component ? `<dt>Component</dt><dd>${escapeHtml(finding.component)}</dd>` : ""}
    </dl>
    ${finding.explanation ? `<p class="explanation">${escapeHtml(finding.explanation)}</p>` : ""}
    ${finding.mitigation ? `<p class="fix"><strong>How to fix it:</strong> ${escapeHtml(finding.mitigation)}</p>` : ""}
    <details>
      <summary>Evidence</summary>
      <pre>${escapeHtml(finding.evidence)}</pre>
    </details>
  </section>`;
}

export function renderScanReportHtml(scan, { owner } = {}) {
  const findings = [...(scan.findings ?? [])].sort((a, b) => severityRank(a) - severityRank(b));

  const countRows = SEVERITIES.filter((s) => (scan.counts?.[s] ?? 0) > 0)
    .map(
      (s) =>
        `<tr><td><span class="dot" style="background:${SEVERITY_COLOURS[s]}"></span>${s}</td>` +
        `<td>${scan.counts[s]}</td></tr>`
    )
    .join("");

  const target =
    scan.target?.packageName || scan.target?.apkFileName || scan.target?.deviceSerial || "not recorded";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>BioAudit report ${escapeHtml(scan.id)}</title>
<style>
  body { font-family: "Segoe UI", Arial, sans-serif; color: #202124; max-width: 60rem;
         margin: 2rem auto; padding: 0 1.5rem; line-height: 1.55; }
  h1 { color: #0b57d0; margin-bottom: .25rem; }
  .subtitle { color: #5f6368; margin-top: 0; }
  table { border-collapse: collapse; margin: 1rem 0; }
  th, td { border: 1px solid #e0e0e0; padding: .4rem .8rem; text-align: left; }
  th { background: #f1f3f4; }
  .dot { display: inline-block; width: .6rem; height: .6rem; border-radius: 50%;
         margin-right: .5rem; }
  .finding { border: 1px solid #e8eaed; border-radius: 6px; padding: 1rem 1.25rem;
             margin: 1rem 0; }
  .finding h3 { margin: 0 0 .5rem; font-size: 1.05rem; }
  .badge { color: #fff; font-size: .7rem; font-weight: 700; padding: .1rem .45rem;
           border-radius: 10px; margin-right: .5rem; vertical-align: middle; }
  dl { display: grid; grid-template-columns: max-content 1fr; gap: .1rem .75rem;
       font-size: .9rem; margin: .5rem 0; }
  dt { color: #5f6368; }
  dd { margin: 0; }
  pre { background: #f1f3f4; padding: .75rem; border-radius: 4px; overflow-x: auto;
        font-size: .8rem; white-space: pre-wrap; }
  .fix { background: #e8f0fe; border-left: 4px solid #0b57d0; padding: .6rem .9rem;
         border-radius: 3px; }
  footer { color: #5f6368; font-size: .8rem; border-top: 1px solid #e8eaed;
           margin-top: 2rem; padding-top: 1rem; }
</style>
</head>
<body>
  <h1>Biometric authentication security report</h1>
  <p class="subtitle">Generated by BioAudit</p>

  <table>
    <tr><th>Scan reference</th><td>${escapeHtml(scan.id)}</td></tr>
    <tr><th>Check type</th><td>${scan.type === "device" ? "Live device assessment" : "App file check"}</td></tr>
    <tr><th>Target</th><td>${escapeHtml(target)}</td></tr>
    <tr><th>Run by</th><td>${escapeHtml(owner?.displayName || owner?.email || scan.userId)}</td></tr>
    <tr><th>Started</th><td>${escapeHtml(formatDate(scan.startedAt ?? scan.createdAt))}</td></tr>
    <tr><th>Finished</th><td>${escapeHtml(formatDate(scan.finishedAt))}</td></tr>
    <tr><th>Authorisation confirmed</th><td>${scan.authorisationConfirmed ? "Yes" : "Not applicable"}</td></tr>
  </table>

  <h2>Summary</h2>
  ${
    countRows
      ? `<table><tr><th>Severity</th><th>Count</th></tr>${countRows}</table>`
      : "<p>No problems were found in this check.</p>"
  }

  <h2>Findings (${findings.length})</h2>
  ${findings.map(renderFinding).join("") || "<p>Nothing to report.</p>"}

  <footer>
    <p>Detection is rule based and repeatable. The written explanations are generated by an
    AI layer from the evidence above, with secrets removed before sending, and the AI does
    not decide what counts as a problem.</p>
    <p>Only test applications you own or are authorised to test.</p>
  </footer>
</body>
</html>`;
}
